import type { Metadata, Viewport } from 'next';
import { Bricolage_Grotesque, Spectral, JetBrains_Mono, Newsreader } from 'next/font/google';
import './globals.css';
import './prototypes/prototypes.css';
import contentConfig from '@/config/contentConfig';

const bricolage = Bricolage_Grotesque({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-bricolage',
  display: 'swap',
});

const spectral = Spectral({
  weight: ['300', '400', '500', '600'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-spectral',
  display: 'swap',
});

// Aliased so older Atelier components that referenced --font-news keep working
const newsreader = Newsreader({
  weight: ['300', '400', '500', '600'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-news',
  display: 'swap',
});

const mono = JetBrains_Mono({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: `${contentConfig.personal.name} - Portfolio`,
  description: contentConfig.hero.subheadline,
  keywords: [
    'Sahaj Shukla',
    'Data Analyst',
    'Audit Analyst',
    'IT Auditor',
    'Technology Audit',
    'Data Engineering',
    'AI',
    'Machine Learning',
    'Python',
    'SQL',
    'Spark',
    'Portfolio',
  ],
  authors: [{ name: contentConfig.personal.name }],
  // Favicon is generated by src/app/icon.tsx (the Next.js icon convention).
  openGraph: {
    title: `${contentConfig.personal.name} - Portfolio`,
    description: contentConfig.hero.subheadline,
    type: 'website',
    locale: 'en_US',
    images: ['/icon.png'],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${contentConfig.personal.name} - Portfolio`,
    description: contentConfig.hero.subheadline,
    images: ['/icon.png'],
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`scroll-smooth ${bricolage.variable} ${spectral.variable} ${newsreader.variable} ${mono.variable}`}
    >
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
